### ISSUE TITLE
'Arrow key' commands are not interpreted

### ISSUE THREAD

**Issue by UrfinJuice11** [calebstewart/pwncat#100]
**Describe the bug**
When using the arrow keys to move cursor within the written string or trying to show the last command only the arrow key codes are shown on the screen. 
Also the command prompt contains extra symbols.

**Describe the target system**
Tested target systems were different. The last one was:
**Linux ekzameno 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux**
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"

**The host system**
Linux kali 5.10.0-kali7-amd64 #1 SMP Debian 5.10.28-1kali1 (2021-04-12) x86_64 GNU/Linux
Using **terminator** of version 2.1.0

**Screenshots**

![image](https://user-images.githubusercontent.com/33019945/120747182-4355b500-c509-11eb-8933-e206c61171ba.png)

**Comment by calebstewart** [comment]
Can you tell me what reverse shell method you are using? I think I've got a fix done for this. I'm testing on a Ubuntu 14.04 docker image, but I want to replicate your situation as much as possible.

I have a branch named [issue-100-arrow-keys](https://github.com/calebstewart/pwncat/tree/issue-100-arrow-keys) which has the small fix. Basically, it checks to see if you are executing in `sh`, and if you are, it tries to locate `bash`. If it can find bash, it executes that instead, and continues running like normal. If it can't find `bash`, colors in the remote terminal are disabled, and a warning is printed about the arrow keys, since `sh` often doesn't support nice interactive things like that.

**Comment by UrfinJuice11** [comment]
I have tested the issue once again. Used sh and bash for reverse shell. Bash worked as intended, but sh had the issue. Suppose your solution will work well. 

/bin/sh

![sh](https://user-images.githubusercontent.com/33019945/121141262-72d72b00-c843-11eb-9ac1-1095390077ff.png)

/bin/bash

![bash](https://user-images.githubusercontent.com/33019945/121141290-79fe3900-c843-11eb-95bf-250bda30aecf.png)

Also I am interested if the rlwrap functionality can help with tab completion and arrow commands when using sh?

**Comment by calebstewart** [comment]
To contrast the above screenshot, if `bash` is not installed on the target (which is unlikely), you should see this:

![image](https://user-images.githubusercontent.com/7529189/121146741-3a692a00-c80e-11eb-97de-b172aec8a79e.png)

**Comment by UrfinJuice11** [comment]
Yep, now working good. 
Thanks for help!
