### ISSUE TITLE
Issue with shell prompt, color codes, host hash

### ISSUE THREAD

**Issue by Mitul16** [calebstewart/pwncat#126]
## Describe the bug
While I was testing the `master` branch (commit 6609591cef857e7ebc39c47f0a8cdf7982f83a42), I found some minor issues

- `pwncat` doesn't _always_ modify the shell prompt - `PS1` successfully (it does try to _upgrade_ the shell but doesn't succeed always)
- `run enumerate.system.network` got some issue with the module `rich`
- pardon me if I am understanding it wrong but the _host hash_ is kind of buggy, you can see in the image as well (with the same host we get: `loaded known host from db` as well as `registered new host w/ db`)

#### Describe the target system
```
uname -a
# Linux kali-vm 5.10.0-kali8-amd64 #1 SMP Debian 5.10.40-1kali1 (2021-05-31) x86_64 GNU/Linux

bash --version
# GNU bash, version 5.1.0(1)-rc2 (x86_64-pc-linux-gnu)
```

## To Reproduce
> issue with shell prompt - `PS1`

#### Steps to reproduce the behavior:
1. Start a new session, `pc connect://IP:PORT`
2. Press `Ctrl-D` to get back into the _remote terminal_
3. See the error (`export PS1=...` is displayed)

#### Expected behavior:
The shell should be upgraded to `bash` (it is available in my case) and requires support for other shells like `zsh`

<hr></hr>

> issue with displaying the `inet6?` values

#### Steps to reproduce the behavior:
1. Get a session, and run `run enumerate.system.network`
2. See the error (color codes are printed)

#### Expected behavior:
The color codes should be rendered properly, though this is an issue from the module `rich`

<hr></hr>

> removed a non-issue

## Screenshots
![Screenshot from 2021-06-14 17-19-10](https://user-images.githubusercontent.com/44923300/121887967-0e313a00-cd35-11eb-951e-01b48e097f99.png)

**Comment by calebstewart** [comment]
I've added a pull request which fixes the shell oddities you saw. `zsh` is the default shell in Kali, not bash. `zsh` uses a different syntax from other shells for embedded colors. I've added a lookup table keyed by basename of the active shell. Currently, this only includes `sh` (uncolored prompt), `zsh` and `default`, but should fix your problem with the prompt. Regarding the `enumerate.system.network` enumeration, Kali apparently has colors turned on for the `ip` command by default. I added the `-c=never` argument to that call which should stop `ip` from outputting them for systems with that enabled.

If you have the time, please give #127 a try and let me know over there if that pull request fixes the shell prompt and network enumeration problems.

For the host hash question, there's a couple things to note. Firstly, you are running pwncat from two separate directories. If you are using the default configuration file from the root of the repository, then the database is kept in a directory relative to your CWD, so each instance is using a separate database. 

If neither of those two directories have a `pwncatrc` in them, and you haven't defined a user or system configuration file (in either `~/.config/pwncat/pwncatrc` or `/etc/pwncat/pwncatrc`), then the default is to use an in-memory database which obviously will not persist across sessions.

The other thing to note about the databases is that I admittedly haven't tested connecting multiple instances of pwncat to the same database. I believe the database files are locked while open. That wasn't necessarily a goal, especially since pwncat supports multiple sessions anyway. What is your rationale behind the command you are running? Why start another shell from within your first shell?

**Comment by Mitul16** [comment]
Regarding the _config_ file `pwncatrc`, shouldn't the general behaviour be checking the _configs_ in the following order:
- `-c/--config CONFIG_FILE`
- `./pwncatrc` - project configuration
- `~/.local/share/pwncat/pwncatrc` - user configuration
- `/etc/pwncat/pwncatrc` - system configuration

I do have a __system-wide__ _config_ file to modify the database parameter
`db` = `file:///opt/cybersec/pwncat/pwncat-db/pwncat-db`

And it seems as if it was _overriden_ with the values from the _default_ `./pwncatrc` file in the _git repo directory_ I was currently in
I did update the _hostname_ for my VM (to remove confusion with my system) before this particular test as shown in the above image
I apologize for the misunderstanding there, regarding the _host hash_ check from the _database_

And for the issue regarding `zsh` being the default in _Kali_, I know this.
But once while testing, I received a message from `pwncat` - `upgrading from sh to /usr/bin/bash`
I thought this is supposedly done, to use `bash` as the _default choice_ but it is not

I am not sure about why did I receive it, perhaps there was an issue with an underlying `recv` method or something else; trying `getenv("SHELL")` and the result being resolved to `""` or `None`

Given that `SHELL` was not resolved correctly, the following code snippet from `pwncat/platform/linux.py` shows that message

```python
 544         self.shell = self.getenv("SHELL")
 545         if self.shell == "" or self.shell is None:
 546             self.shell = "/bin/sh"
 547
 548         # This doesn't make sense, but happened for some people (see issue #116)
 549         if os.path.basename(self.shell) == "nologin":
 550             self.shell = "/bin/sh"
 551             self.channel.sendline(b" export SHELL=/bin/sh")
 552
 553         if os.path.basename(self.shell) == "sh":
 554             # Try to find a better shell
 555             bash = self._do_which("bash")
 556             if bash is not None:
 557                 self.shell = bash
 558                 self.session.log(f"upgrading from sh to {self.shell}")
 559                 self.channel.sendline(f"exec {self.shell}".encode("utf-8"))
 560                 time.sleep(0.5)
 561
```

Lastly, about me trying to start a new _shell_ from the existing one.
Instead of using `ssh -i ...` to connect to my VM, I preferred `pwncat`. I was just testing various protocols :sweat_smile:

Here is the image showing `pwncat` variables with my custom configurations

![Screenshot from 2021-06-15 00-37-16](https://user-images.githubusercontent.com/44923300/121951169-31c9a400-cd78-11eb-88ac-648ac0565ab4.png)

**Comment by calebstewart** [comment]
## Configuration Discussion

The order of precedence is correct. Technically speaking, they are all loaded with the exception of `./pwncatrc`. What happens is this:

- Execute `/etc/pwncat/pwncatrc` if it exists
- Execute `$XDG_DATA_HOME/pwncat/pwncatrc` if it exists
- Execute explicit configuration if provided, else execute `./pwncatrc` if it exists.

With this logic, if a configuration file is specified, the configurations set in it will take precedence over the other configuration files, but any non-overlapping configurations from lower-priority configs will still be present. This is similar to the way profiles work in shells. `/etc/profile` is always executed for a session, but `~/.bash_profile` can override settings from the system profile as well for example. Also, if no configuration file is explicitly specified, pwncat will look in the current directory for a configuration file to use named `pwncatrc`.

This felt natural to me, as outside of development, I wouldn't execute pwncat from the installation directory, and any configuration would have had to be purposefully created, but I'm open to hearing other interpretations and improving the [documentation on the subject](https://pwncat.readthedocs.io/en/latest/configuration.html). I just realized however that the documentation doesn't mention `/etc/pwncat/pwncatrc` at all, so that *does* need updating.

## Shell Discussion

That message likely indicated that the `SHELL` environment variable was either not set or set to `/bin/sh`. pwncat does these shell checks very early in setup, and identifying the currently running process is difficult in this early fragile state. We trust the `SHELL` environment variable, because it's ~~almost~~ always set appropriately. In the case where it isn't, the worst case is that we end up with no colors, and that can be easily fixed by running `exec /bin/bash` at the remote prompt. The best case is that `pwncat` locates bash on it's own, and we end up hopping into bash regardless. This is harmless in most cases, so I think the small number of false positives is worthwhile.

## ~~Dream~~Shell within a ~~Dream~~Shell

Relevant meme to lighten up these very long messages:
![image](https://user-images.githubusercontent.com/7529189/121957067-ea1f2a00-cd2f-11eb-81f3-e847a1b35027.png)

## Conclusion of This Essay

In the interest of not continuing down the path of very long messages, to summarize:
- #127 fixes the shell prompt issue and `enumerate.system.network` module output issue
- The host hash problems were a non-issue due to database configuration
- Multiple simultaneous connections to one local database is likely to fail due to file locking.
- `SHELL` resolution can fail, but the resulting actions taken by pwncat are a "best of a bad situation" decision and should not detrimentally effect the session (in fact, more often than not, they correct problems).

With this in mind, I am going to merge #127 and close this issue. If you have further issues with shell resolution, please let me know and we can possibly reopen this issue. I appreciate your time working with this. It's always great to hear someone has the tool embedded in their workflow and is using some of the more obscure features like system-wide configurations. :smiley:

**Comment by Mitul16** [comment]
There is one more issue with the shell prompt

If an `attacker` switches their shells (e.g. from `zsh` to `bash` or `bash` to `sh`) then `pwncat` uses the same `PS1` value resolved with the help of `$SHELL` during the _initital setup_

An `attacker` may require to do this in case when a _shell binary_ other than the one specified by `$SHELL` is a `SUID` binary and the `attacker` switched back to `pwncat` terminal to perform enumeration using the _newly acquired user_

`self.shell` variable needs to updated for this reason, which will in turn update the `prompt`

> `pwncat/platform/linux.py`
```python
1530             prompt = self.PROMPTS.get(
1531                 os.path.basename(self.shell), self.PROMPTS["default"]
1532             )
```

**Comment by calebstewart** [comment]
I think I've hammered this out now. I'm opening a pull request now. There were a couple problems.

1. Apparenlty, shells don't always set `SHELL`. This was an unreliable way to determine the current shell.
2. There was a bug in my implementation of `ChannelFile` which caused `getenv` to sporadically return an empty string. 
Basically, the `recvinto` method was raising a `BlockingIOError` in an edge case, which it should not have been doing.

In the end, I moved the shell detection to happen whenever interactive mode is disabled. This basically means whenever the user exits the remote prompt, it will check what shell is currently running. Further, it now first attempts to check the shell by using `Path("/proc/$$/exe").readlink()`. This should provide the full path to the shell. If this fails (e.g. procfs is not mounted for some reason), we fall back to `SHELL`. This no longer happens directly in `__init__`, but is triggered by setting `self.interactive = False` within `__init__`. The checks for upgrading from `sh` or `dash` still happen in `__init__` after `self.shell` is initialized indirectly. I'm not seeing any inconsistencies anymore, but you can checkout the branch as well and let me know.
