### ISSUE TITLE
[BUG] C-d from remote prompt after connection closed causes uncaught exception

### ISSUE THREAD

**Issue by calebstewart** [calebstewart/pwncat#133]
## Describe the bug
If you are connected to a victim, and the remote shell is killed, if you press `C-d` to exit the remote shell, an uncaught `ChannelError` is raised. The routine in `Manager.interactive` needs to be modified to catch these exceptions.

In most places, exceptions are caught, but there was some wiggle-room left during transition between states, which causes this problem.

## Describe the target system
Any target will trigger this error if the remote shell/process is killed and the next input from the attacker is `C-d`. 

## Steps To Reproduce
1. **On victim**: `socat TCP-LISTEN:4444,reuseaddr,fork EXEC:/bin/bash`
2. **On Attacker**: `pwncat W.X.Y.Z 4444`
3. **On Attacker**: Press `C-d` to go to remote prompt
4. **On victim**: Press `C-c` to kill `socat`
5. **On Attacker**: Press `C-d` to return to pwncat prompt

This will cause the uncaught `ChannelError`, and exit pwncat completely. It's worth noting that if any other keys are pressed besides `C-d`, pwncat will recognize the channel has closed and continue correctly.

## Expected behavior
Exception is caught just as if you pressed any other key.

## Screenshots
![image](https://user-images.githubusercontent.com/7529189/122279423-04831000-ceb6-11eb-8a9a-4111467e4951.png)

## Expected Solution
The problem is at lines 593-612 of `manager.py`:

```py
            try:
                self.target.platform.interactive_loop(interactive_complete)
            except RawModeExit:
                pass
            except ChannelClosed:
                channel_closed = True
                self.log(
                    f"[yellow]warning[/yellow]: {self.target.platform}: connection reset"
                )
            except Exception:
                pwncat.util.console.print_exception()

            # Trigger thread to exit
            interactive_complete.set()
            output_thread.join()

            # Exit interactive mode
            if channel_closed:
                self.target.died()
            else:
                self.target.platform.interactive = False
```

The `Exit interactive mode` block should be within the `try`-block. Something like this:

```py
            try:
                try:
                    self.target.platform.interactive_loop(interactive_complete)
                except RawModeExit:
                    pass
                self.target.platform.interactive = False
            except ChannelClosed:
                self.target.died()
                self.log(
                    f"[yellow]warning[/yellow]: {self.target.platform}: connection reset"
                )
            except Exception:
                pwncat.util.console.print_exception()

            # Trigger thread to exit
            interactive_complete.set()
            output_thread.join()
```

**Comment by calebstewart** [comment]
Thanks to @Mitul16 for pointing this out over in PR #132.

**Comment by Mitul16** [comment]
Firstly, I got into some other work causing delay in your tests.
Secondly, I have tested this branch and it seems to have fixed the dicussed issues.
But, with a little bit of digging I found somewhat similar results (getting kicked out from my `pwncat` instance)

If you want to use it, here is the [error.log](https://github.com/calebstewart/pwncat/files/6669623/error.log) for the output shown in the images below.

I should have created another __Issue__, instead I am presenting here since it is a fairly similar issue if not the same

## Steps to reproduce
- Start a _bind shell listener_ on the `victim` machine - `socat tcp-l:PORT,fork exec:/bin/sh`
- Connect  to the _bind shell_ - `pc connect://IP:PORT`
- Kill the connection from the `victim` machine - `Ctrl-C` to kill the process
- Run an enumeration - `run enumerate.file.suid`
- Wait for `ChannelTimeout` to occur (it occurs after the set 30 seconds timeout) - ...
- Observe that the invalidated session still exists - `sessions`
- Try to interact with this invalidated session - `sessions 0`
- See the error - `pwncat` instance exits out

![Screenshot from 2021-06-17 16-27-09](https://user-images.githubusercontent.com/44923300/122384678-8f810a80-cf89-11eb-9ab1-dd29bd05c8bf.png)

![Screenshot from 2021-06-17 16-27-18](https://user-images.githubusercontent.com/44923300/122384675-8ee87400-cf89-11eb-8990-fd5d714a4c3d.png)

![Screenshot from 2021-06-17 16-27-39](https://user-images.githubusercontent.com/44923300/122384672-8e4fdd80-cf89-11eb-8391-21f31fb224e9.png)

![Screenshot from 2021-06-17 16-27-46](https://user-images.githubusercontent.com/44923300/122384666-8d1eb080-cf89-11eb-9e46-1745d3172ed8.png)

**Comment by Mitul16** [comment]
After a connection error, we should close the respective session if it is not closed and prevent the user from interacting with it.

**Comment by calebstewart** [comment]
I pushed an update. There was some incorrect handling of the results of `socket.recv` in `pwncat.channel.socket.Socket.recv`. It now raises the appropriate `ChannelClosed` exception, and in my tests closed the channel properly.

![image](https://user-images.githubusercontent.com/7529189/122464484-e59f7f00-cf84-11eb-9ccb-530ed9cfa7c3.png)

**Comment by calebstewart** [comment]
This should also prevent the obnoxiously long 30-second timeout when a connection drops, which is something that I couldn't figure out how to fix before, so I'm happy it's gone. :rofl:

**Comment by calebstewart** [comment]
Just did some more testing. There is still the other error you mentioned when trying to go back to the remote prompt after the shell dies. I'll work on that now.
