### ISSUE TITLE
Listeners

### ISSUE THREAD

**Issue by juushya** [calebstewart/pwncat#43]
## Functionality

At present, we can start and administer only one listener at a time - `pwncat --listen --port <port>`. It will be useful to have the following, if possible:

1. The capability to start multiple listeners in one go (command-separated ports, or range of ports) (similar feature seen in cytopia/pwncat)

    - Comma separated
pwncat -l 4444 /bin/bash:10.0.0.1:4445,4446,4447,4448

    - Range
pwncat -l 4444 /bin/bash:10.0.0.1:4445-4448

    - Increment
pwncat -l 4444 /bin/bash:10.0.0.1:4445+3

2. A central summary of all the active/inactive, persistent/non-persistent) shells (think: Metasploit Framework *sessions* or Empire)

3. Capability to execute a set of commands (enum / privesc etc) on all the active shells (think: Metasploit Framework *auxiliary/post* modules)

**Comment by calebstewart** [comment]
I'm going to be honest and say I don't personally see a ton of use in this. I understand it's a feature which other tools provide, but even in those other tools I don't find it overly useful (with the exception of auto-routing in metasploit which I think is out of scope for pwncat in it's current state). Not to mention the fact that I find switching between shells via things like `sessions` or something clunky/awkward. I would much rather just pop open another pane/tab/window and run another listener.

That being said, I won't close this issue immediately. I'm not closed off to the idea, and just because I created the project doesn't mean I automatically know best :rofl: This change would require a major overhaul of the code that I'm not ready to do at the moment. There's other goals that I think have more benefit in the short term. I'll leave this on the list, though. If I can eventually get to it, I will.

**Comment by calebstewart** [comment]
Just going through stale issues, and I wanted to poke my head in here. This isn't forgotten. There's a big reorganization of the framework that came with implementing multi-platform support. This includes implementing multi-session support as well (including some things you mentioned like a `sessions` command to manage active sessions).

Currently, that stuff is working (however in the early-ish stages of development) in the `platforms` branch. What isn't implemented is the ability to start multiple listeners at once. Instead, you can sequentially start and connect multiple sessions. I would like to implement background jobs at some point, but I need to get the entire platforms branch merged back to main before I can take up another big project like that.

**Comment by calebstewart** [comment]
Just merged this into the v0.5.0 release branch. It will be present in the next major release. I'm going to close this issue. :+1:
