### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sansekertha** [calebstewart/pwncat#65]
File "setup.py", line 67
    dependency_links[i] = f"{link}/tarball/master#egg={name}"
                                                            ^
SyntaxError: invalid syntax
(pwncat-env)

**Comment by JohnHammond** [comment]
Jumping in here because this snippet of an error message doesn't offer a ton of context -- are you using Python 2? This error does not seem to popped up for other users and the syntax error may be coming from trying to use an f-string while Python 2 does not have support for that. Python 3 does and pwncat runs with Python 3.8.

**Comment by sansekertha** [comment]
Hello John,
this is my python version
should i upgrade to 3.8 ?


~/pwncat$ python3 --version
Python 3.5.2

**Comment by sansekertha** [comment]
it works now

Thanks Johns
