### ISSUE TITLE
Hang while switching to raw mode

### ISSUE THREAD

**Issue by UrfinJuice11** [calebstewart/pwncat#70]
**Describe the issue**
After catching reverse shell if switch to command mode and then back to raw mode with Ctrl+d, we see some password query, if hit Enter - we can not see printed characters so no response.

Describe the target system
Worker the HTB

1. Getting working reverse shell
![image](https://user-images.githubusercontent.com/33019945/97464773-61937b00-1952-11eb-9f02-f22aa4ed8373.png)
2. Switching to command mode and use privesc
![image](https://user-images.githubusercontent.com/33019945/97465027-aa4b3400-1952-11eb-909e-3f76aeef0ded.png)
3. Switch back to raw mode
![image](https://user-images.githubusercontent.com/33019945/97465266-ebdbdf00-1952-11eb-908b-b9aace96493b.png)

Could you please tell, if that is a bug or am I doing smth wrong?

**Comment by trevorbryant** [comment]
This isn't a "bug" per se, but we've been treating it as one. This has to do with the latency of the victim machines. It's something that's been on our radar and we have been testing through.

Stay tuned!

**Comment by UrfinJuice11** [comment]
Ok. Thanks for your reply and the project itself!

**Comment by calebstewart** [comment]
To provide a little more context, if you're inclined/curious, I'll explain what's happening. As @trevorbryant mentioned, it has to do with latency. The way that pwncat is checking to see if a password is required for sudo is returning a false negative occasionally due to high latency, which causes pwncat to think that no password is required. As a result, pwncat is waiting for the command to finish while sudo is waiting for pwncat to send a password. This is the definition of a deadlock. As trevor mentioned, you can continue operation by going back to your raw shell and cancelling the sudo operation.

As a side-effect of implementing the platform and channel abstractions that I'm working on now, this logic is being rewritten, and hopefully will be more stable across slow connections. In the meantime, I don't have a good fix.

**Comment by UrfinJuice11** [comment]
**As trevor mentioned, you can continue operation by going back to your raw shell and cancelling the sudo operation.**
How can I cancel the sudo operation?
At the moment of "hanging" no visible commands are in the local mode, and no reaction for any keys in the remote mode...

**Comment by calebstewart** [comment]
Sudo has a timeout, but if you press enter a few times, it should exit. Or alternatively press Ctrl-C.

Because it failed mid-enumerate, the prompt was disabled and echoing may also be off. However, if you press Ctrl-D after sudo exits, then run `reset` from the pwncat local prompt, it will put the terminal back to normal.

**Comment by UrfinJuice11** [comment]
OK, thanks for help.
