### ISSUE TITLE
[BUG] ASPX reverse shell stuck on initializing hostname

### ISSUE THREAD

**Issue by itasahobby** [calebstewart/pwncat#78]
**Describe the bug**
Tried to establish a reverse shell with pwncat, however it stays stuck on initializing: hostname.
However if I just simply start a netcat listener `nc -lvnp 8080` i get the reverse shell just fine.

This was found while doing `Worker` from htb.

1. Upload the [aspx reverse shell](https://github.com/borjmz/aspx-reverse-shell/blob/master/shell.aspx)
2. Start pwncat
3. Curl the reverse shell

Screenshots to show the problem
![image](https://user-images.githubusercontent.com/47305925/103533951-4c752400-4e8e-11eb-81d4-ac4eb3ed0042.png)

**Comment by trevorbryant** [comment]
@itasahobby, `pwncat` is currently scoped for Linux targets. That's why you experience the hang on host initialization.

There are plans to  include Windows support in the future. I need to get back to updating the overall progress on the [project board](https://github.com/calebstewart/pwncat/projects/1), but in the meantime just hang tight.
